spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# databse url setup
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true
spring.jpa.database = MYSQL
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ankurbanssla@gmail.com
spring.mail.password=lidb ljab bvli tcmg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false


# School Code Configurations
school.codes.CODE_101.database-url=jdbc:mysql://localhost:3306/school_101_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
school.codes.CODE_101.school-name=School 101
school.codes.CODE_101.username=root
school.codes.CODE_101.password=test

school.codes.CODE_102.database-url=jdbc:mysql://localhost:3306/school_102_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
school.codes.CODE_102.school-name=School 102
school.codes.CODE_102.username=root
school.codes.CODE_102.password=test

school.codes.CODE_103.database-url=jdbc:mysql://localhost:3306/school_103_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
school.codes.CODE_103.school-name=School 103
school.codes.CODE_103.username=root
school.codes.CODE_103.password=test