export const LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const LOGOUT_USER = "SET_LOGOUT_USER";


export const GET_CLASSES = "GET_CLASSES";
export const GET_SECTION = "GET_SECTION";
export const GET_LINK = "GET_LINK";

export const CREATED_SUCCESSFULLY = "CREATED_SUCCESSFULLY";
export const SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG";

export const FORGET_PASSWORD = "FORGET_PASSWORD";

export const GET_ALL_ENTITY = "GET_ALL_ENTITY";

export const NO_DATA_FOUND = "NO_DATA_FOUND";

export const GET_STUDENT = "GET_STUDENT";
export const GET_TEACHER = "GET_TEACHER";

export const RESET_STATE = 'RESET_STATE';

export const CREATE_USER = 'CREATE_USER';

export const GET_ALL_USER_DETAILS = "GET_ALL_USER_DETAILS";

export const GET_ALL_USER_PROFILE = "GET_ALL_USER_PROFILE";