export const LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const LOGOUT_USER = "SET_LOGOUT_USER";
export const GET_ROLE = "GET_ROLE";


export const GET_CLASSES = "GET_CLASSES";
export const GET_SECTION = "GET_SECTION";
export const GET_LINK = "GET_LINK";

export const CREATED_SUCCESSFULLY = "CREATED_SUCCESSFULLY";
export const SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG";

export const FORGET_PASSWORD = "FORGET_PASSWORD";

export const GET_ALL_ENTITY = "GET_ALL_ENTITY";

export const NO_DATA_FOUND = "NO_DATA_FOUND";

export const GET_STUDENT = "GET_STUDENT";
export const GET_TEACHER = "GET_TEACHER";

export const RESET_STATE = 'RESET_STATE';

export const CREATE_USER = 'CREATE_USER';


export const GET_ALL_USER_DETAILS = "GET_ALL_USER_DETAILS";

export const GET_ALL_USER_PROFILE = "GET_ALL_USER_PROFILE";
export const LINK_CLASS_SECTION = "LINK_CLASS_SECTION";
export const GET_ONE_TIME_FEE = "GET_ONE_TIME_FEE";
export const GET_MONTHLY_FEE = "GET_MONTHLY_FEE";

export const SUPER_ADMIN = "SUPER_ADMIN";
export const TEACHER = "TEACHER";
export const STUDENT = "STUDENT";
export const GET_PARENT = "PARENT";
export const GET_CHILDS_LIST = "GET_CHILDS_LIST";
export const GET_USER_ID = "GET_USER_ID";
export const LOGIN_GET_USER_ID = "LOGIN_GET_USER_ID";

export const SET_TECHER_CLASS_SECTION = "SET_TECHER_CLASS_SECTION";

export const GET_LEAVE_REQUESTS = "GET_LEAVE_REQUESTS";

export const GET_ALL_FEE = "GET_ALL_FEE";
export const ADD_OR_EDIT_FEE = "ADD_OR_EDIT_FEE";
export const GET_ALL_PAYMENT = "GET_ALL_PAYMENT";
export const ADD_OR_UPDATE_PAYMENT = "ADD_OR_UPDATE_PAYMENT";
export const GET_ALL_ATTANDANCE = "GET_ALL_ATTANDANCE";