export const LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const LOGOUT_USER = "SET_LOGOUT_USER";


export const GET_CLASSES = "GET_CLASSES";
export const GET_SECTION = "GET_SECTION";
export const GET_LINK = "GET_LINK";

export const CREATED_SUCCESSFULLY = "CREATED_SUCCESSFULLY";
export const SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG";

export const FORGET_PASSWORD = "FORGET_PASSWORD";